#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTMUX3,         sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorLF,       tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLR,       tmotorTetrix, openLoop, reversed, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorRF,       tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorRR,       tmotorTetrix, openLoop, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorArm1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorArm2,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorLift2,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servo_front_right,    tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo_front_left,     tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo_rear,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    servo_tilt,           tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    servo_trapdoor,       tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    servo_spin,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "JoystickDriver.c"
#include "hitechnic-accelerometer.h"

// For Sensor Multiplexer

#define accel msensor_S3_3 //

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	playSound(soundFastUpwardTones);
	servo[servo_tilt] = 0;
	servo[servo_spin] = 127;
	servo[servo_trapdoor] = 160;

	clearDebugStream();




	servo[servo_front_right] = 80;
	servo[servo_front_left] = 254;


	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

	// Create struct to hold accelerometer sensor data
	tHTAC accelerometer;

	// Initialise and configure struct and port
	initSensor(&accelerometer, accel);

	initializeRobot();
	//
	//  waitForStart();   // wait for start of tele-op phase

	while (true)
	{

		// *********************
		// Read all the information from the joysticks.  This happens every 50ms (or about 20 times
		// per second)
		//
		getJoystickSettings(joystick);
		int deadzone = 20;

		// **********************
		// Driver control -- Joystick 1
		//

		//Tank Drive - Left side

		if (abs(joystick.joy1_y1) > abs(deadzone)) {
			playSound(soundBlip);
			displayBigTextLine(3, "%d, %d", joystick.joy1_y1/1.28, joystick.joy1_y2/1.28);
			motor[motorRF] = -joystick.joy1_y1/1.28;
			motor[motorRR] = -joystick.joy1_y1/1.28;
			} else {
			motor[motorRF] = 0;
			motor[motorRR] = 0;
		}

		//Tank Drive - Right Side

		if (abs(joystick.joy1_y2) > abs (deadzone)) {
			motor[motorLF] = -joystick.joy1_y2/1.28;
			motor[motorLR] = -joystick.joy1_y2/1.28;
			} else {
			motor[motorLF] = 0;
			motor[motorLR] = 0;
		}

		// rear rolling goal atttachment position
		// FIXME: list which one is up and down
		if (joy1Btn(7) == 1) {
			servo[servo_rear] = 0;
			} else if (joy1Btn(8) == 1) {
			servo[servo_rear] = 75;
		}

		// front two rolling goal gripper servos
		// FIXME: list which one is up and down
		if (joy1Btn(5) == 1) {
			servo[servo_front_right] = 80;
			servo[servo_front_left] = 254;
			} else if (joy1Btn(6) == 1) {
			servo[servo_front_right] = 240;
			servo[servo_front_left] = 100;
		}

		// **********************************************************************
		// Arm/Lift/Intake control -- Joystick 2
		//

		// Arm up and down -- manual -- left joystick

		if (joystick.joy2_y1 > deadzone) {
			motor[motorArm1] = 30; //down
			motor[motorArm2] = 30; //down
			} else if (joystick.joy2_y1 < -deadzone) {
			motor[motorArm1] = -60; //up
			motor[motorArm2] = -60; //up
			} else {
			// stop unless a button is overriding it
			if (joy2Btn(7)== 0) {
				motor[motorArm1] = 0;
				motor[motorArm2] = 0;
			}
		}


		// Position values for accellerometer
		// x = 0 horizontal
		// x = 187 vertical
		// x = -145 start position
		// x = -180 lowest


		// automatic positioning to vertical for arm

		if (joy2Btn(7)== 1 && readSensor(&accelerometer)) {
			writeDebugStreamLine("accel = %d\n",accelerometer.x);
			if (accelerometer.x < 185 && accelerometer.z > 0) {
				motor[motorArm1] = -30; //up
				motor[motorArm2] = -30; //up
				} else if (accelerometer.x < 185 && accelerometer.z < 0) {
				motor[motorArm1] = 30;
				motor[motorArm2] = 30;
				} else {
				motor[motorArm1] = 0;
				motor[motorArm2] = 0;
			}
		}


		// automaticaly tilt the tray unless overriden bu button
		readSensor(&accelerometer);
		float tiltpercent = (accelerometer.x + 183.) / 370.;
		int tiltservoval = 200 - (tiltpercent * 200.);
		servo[servo_tilt] = tiltservoval;
		//writeDebugStreamLine("accel X = %d Z = %d percent= %f tiltsesrvoval = %d\n",accelerometer.x, accelerometer.z, tiltpercent, tiltservoval);



		//lift up and down

		if (joystick.joy2_y2 > deadzone) {
			motor[motorLift1] = 60; //down
			motor[motorLift2] = 60; //down
			} else if (joystick.joy2_y2 < -deadzone) {
			motor[motorLift1] = -60; //up
			motor[motorLift2] = -60; //up
			} else {
			motor[motorLift1] = 0;
			motor[motorLift2] = 0;
		}


		/*
		if (joystick.joy2_y2 > deadzone) {
		servo[servo_tilt] = 130;
		} else if (joystick.joy2_y2 < -deadzone) {
		servo[servo_tilt] = 60;
		} else {
		servo[servo_tilt] = 120;
		}
		*/

		// intake control
		//     (1) in/counter clockwise
		//	   (2) out/clockwise

		if (joy2Btn(1) == 1) {
			servo[servo_spin] = 0;  // counter clockwise
			} else if (joy2Btn(2) == 1) {
			servo[servo_spin] = 255;  // clockwise
			} else {
			servo[servo_spin] = 127;  // stop
		}

		if (joy2Btn(3) == 1) {
			servo[servo_trapdoor] = 0;  // open
			} else if (joy2Btn(4) == 1) {
			servo[servo_trapdoor] = 160;  // close
		}



		/*
		if (joy2Btn(3) == 1) {
		// go to position -- 1120 ticks is one rotation for AndyMark Neverest
		//but divide by our 3:1 gear ratio, so 373.33 = 360 degrees
		nMotorEncoder[motorArm1] = 0;
		nMotorEncoder[motorArm2] = 0;

		nMotorEncoderTarget[motorArm1] = 43;
		nMotorEncoderTarget[motorArm2] = 43;

		motor[motorArm1] = 20;
		motor[motorArm2] = 20;
		sleep(1000);
		writeDebugStreamLine("arm = %d\n",nMotorEncoder[motorArm1]);
		}
		if (joy2Btn(4) == 1) {
		// go to position -- 1120 ticks is one rotation for AndyMark Neverest
		nMotorEncoder[motorArm1] = 0;
		nMotorEncoder[motorArm2] = 0;

		nMotorEncoderTarget[motorArm1] = -43;
		nMotorEncoderTarget[motorArm2] = -43;

		motor[motorArm1] = -20;
		motor[motorArm2] = -20;


		sleep(1000);
		writeDebugStreamLine("arm = %d\n",nMotorEncoder[motorArm1]);
		}
		*/
		// motor[motorLF] = 20;
		/*
		servo[servo2]=127;
		servo[servo1]=0;
		sleep(1000);
		servo[servo2]=0;
		servo[servo1]=127;
		sleep(1000);
		float test = sensorValue[gyro];
		eraseDisplay();
		displayBigStringAt(8, 8, "test");
		*/
		// Insert code to have servos and motors respond to joystick and button values.

		// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
		// You may be able to find "snippets" of code that are similar to the functions that you want to
		// perform.



	}
}
